### PR TITLE
docs: credit ArthurKa for helmet#303

### PR DESCRIPTION
**Pull request by ArthurKa**

### CODE REVIEW

**Review by EvanHahn — CHANGES_REQUESTED** [review]
Could you move your name so it's in alphabetical order? You'd be at the end of the A's.

If not, I can do it.

**Comment by ArthurKa** [comment]
Sure :)

**Comment by ArthurKa** [comment]
But is it possible to do if I already delete fork?

**Comment by EvanHahn** [comment]
Hmm, maybe not. I'll take care of it.

**Comment by ArthurKa** [comment]
Thanks! By the way it look like I forgot to add new line at the end of file :(

**Comment by EvanHahn** [comment]
Did this myself in 3dae7df4d9a13cf6d118c5e78f03376a2f8a0f0d. Thanks again for your contribution!

**Pull request closed without merging**
