### PR TITLE
Replace png logo with svg

### PR DESCRIPTION
**Pull request by jucke**
Hi Evan,

I've added svg version of the helmet logo, so that it looks ace on high pixel density screens. Hand-Drawn Goods like this project 😛

J.

### CODE REVIEW

**Comment by EvanHahn** [comment]
This looks good! I'll do a little more testing before I merge.

Could you also remove resources/logo.png?

**Comment by EvanHahn** [comment]
Just tested it and this looks good! Ready to merge once `logo.png` is removed.

Also: would you like to add yourself to the contributors list?

**Comment by jucke** [comment]
Done 🙂

**Comment by EvanHahn** [comment]
Thank so much! SVG for the win.

**Pull request merged**
